---
name: exomast
"@id": "#exomast"
description: "Prototype ExoMAST Database"

tables:
  - name: Sources
    "@id": "#Sources"
    description: Main table for ExoMAST objects (planets, brown dwarfs)
    primaryKey: 
    - "#Sources.id"

    columns:
    - name: id
      "@id": "#Sources.id"
      datatype: int
      description: Main source identifier
      ivoa:ucd: meta.id;meta.main
    - name: type
      "@id": "#Sources.type"
      datatype: string
      length: 30
      description: Type of source (eg, exoplanet, brown dwarf, etc)
      nullable: false
    - name: survey
      "@id": "#Sources.survey"
      datatype: string
      length: 30
      description: Originating survey (eg, nexsci, TOI, etc)
      nullable: false

    indexes:
      - name: PK_Sources_id
        "@id": "#PK_Sources_id"
        description: Primary key for Sources table
        columns: 
        - "#Sources.id"
  
  - name: Matches
    "@id": "#Matches"
    description: Matching table between exomast sources
    primaryKey: 
    - "#Matches.id1"
    - "#Matches.id2"

    columns:
    - name: id1
      "@id": "#Matches.id1"
      datatype: int
      description: Source identifier
      ivoa:ucd: meta.id
    - name: id2
      "@id": "#Matches.id2"
      datatype: int
      description: Source identifier
      ivoa:ucd: meta.id
    
    constraints:
      - name: Matches_id1_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Matches_id1_Source_id"
        description: Link Matches to Sources table
        columns:
        - "#Matches.id1"
        referencedColumns:
        - "#Sources.id"
      - name: Matches_id2_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Matches_id2_Source_id"
        description: Link Matches to Sources table
        columns:
        - "#Matches.id2"
        referencedColumns:
        - "#Sources.id"

  - name: Names
    "@id": "#Names"
    description: "Additional identifiers for objects in Sources table"
    primaryKey:
    - "#Names.id"
    - "#Names.name"

    columns:
    - name: id
      "@id": "#Names.id"
      datatype: int
      description: Main identfier for an object; links to Sources table
      nullable: false
    - name: name
      "@id": "#Names.name"
      datatype: string
      length: 100
      description: Identifier for source
      nullable: false

    constraints:
      - name: Names_id_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Names_id_Source_id"
        description: Link Names to Sources table
        columns:
        - "#Names.id"
        referencedColumns:
        - "#Sources.id"

  - name: Coords
    "@id": "#Coords"
    description: Coordinates for ExoMAST objects (planets, brown dwarfs)
    primaryKey: 
    - "#Coords.id"

    columns:
    - name: id
      "@id": "#Coords.id"
      datatype: int
      description: Main source identifier
      ivoa:ucd: meta.id;meta.main
    - name: ra
      "@id": "#Coords.ra"
      datatype: double
      description: ICRS Right Ascension of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.ra;meta.main
    - name: dec
      "@id": "#Coords.dec"
      datatype: double
      description: ICRS Declination of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.dec;meta.main

    constraints:
      - name: Coords_id_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Coords_id_Source_id"
        description: Link Coords to Sources table
        columns:
        - "#Coords.id"
        referencedColumns:
        - "#Sources.id"
      - name: check_ra
        "@type": Check
        "@id": "#Sources_check_ra_bounds"
        description: Validate RA range
        expression: ra >= 0 AND ra <= 360
      - name: check_dec
        "@type": Check
        "@id": "#Sources_check_dec_bounds"
        description: Validate Dec range
        expression: dec >= -90 AND dec <= 90
