---
name: exomast
"@id": "#exomast"
description: "Prototype ExoMAST Database"

tables:
  - name: Sources
    "@id": "#Sources"
    description: Main table for ExoMAST objects (planets, brown dwarfs)
    primaryKey: 
    - "#Sources.id"

    columns:
    - name: id
      "@id": "#Sources.id"
      datatype: long
      description: Main source identifier
      ivoa:ucd: meta.id;meta.main
    - name: source_type
      "@id": "#Sources.source_type"
      datatype: string
      length: 30
      description: Type of source (eg, exoplanet, brown dwarf, etc)
      nullable: false
    - name: survey
      "@id": "#Sources.survey"
      datatype: string
      length: 30
      description: Originating survey (eg, nexsci, TOI, etc)
      nullable: false
    - name: primary_name
      "@id": "#Sources.primary_name"
      datatype: string
      length: 100
      description: Primary name for this source from survey
      nullable: false
    - name: modification_date
      "@id": "#Sources.modification_date"
      datatype: timestamp
      description: Timestamp from when this source was produced
      nullable: false

    indexes:
      - name: PK_Sources_id
        "@id": "#PK_Sources_id"
        description: Primary key for Sources table
        columns: 
        - "#Sources.id"
  
  - name: Matches
    "@id": "#Matches"
    description: Matching table between exomast sources
    primaryKey: 
    - "#Matches.id1"
    - "#Matches.id2"

    columns:
    - name: id1
      "@id": "#Matches.id1"
      datatype: long
      description: Source identifier
      ivoa:ucd: meta.id
    - name: id2
      "@id": "#Matches.id2"
      datatype: long
      description: Source identifier
      ivoa:ucd: meta.id
    
    constraints:
      - name: Matches_id1_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Matches_id1_Source_id"
        description: Link Matches to Sources table
        columns:
        - "#Matches.id1"
        referencedColumns:
        - "#Sources.id"
      - name: Matches_id2_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Matches_id2_Source_id"
        description: Link Matches to Sources table
        columns:
        - "#Matches.id2"
        referencedColumns:
        - "#Sources.id"

  - name: Names
    "@id": "#Names"
    description: "Additional identifiers for objects in Sources table"
    primaryKey:
    - "#Names.id"
    - "#Names.name"

    columns:
    - name: id
      "@id": "#Names.id"
      datatype: long
      description: Main identifier for an object; links to Sources table
      nullable: false
    - name: name
      "@id": "#Names.name"
      datatype: string
      length: 100
      description: Identifier for source
      nullable: false

    constraints:
      - name: Names_id_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Names_id_Source_id"
        description: Link Names to Sources table
        columns:
        - "#Names.id"
        referencedColumns:
        - "#Sources.id"

  - name: Coords
    "@id": "#Coords"
    description: Coordinates for ExoMAST objects
    primaryKey: 
    - "#Coords.id"

    columns:
    - name: id
      "@id": "#Coords.id"
      datatype: long
      description: Main source identifier
      ivoa:ucd: meta.id;meta.main
    - name: ra
      "@id": "#Coords.ra"
      datatype: double
      description: ICRS Right Ascension of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.ra;meta.main
    - name: dec
      "@id": "#Coords.dec"
      datatype: double
      description: ICRS Declination of object
      fits:tunit: deg
      ivoa:ucd: pos.eq.dec;meta.main

    constraints:
      - name: Coords_id_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_Coords_id_Source_id"
        description: Link Coords to Sources table
        columns:
        - "#Coords.id"
        referencedColumns:
        - "#Sources.id"
      - name: check_ra
        "@type": Check
        "@id": "#Sources_check_ra_bounds"
        description: Validate RA range
        expression: ra >= 0 AND ra <= 360
      - name: check_dec
        "@type": Check
        "@id": "#Sources_check_dec_bounds"
        description: Validate Dec range
        expression: dec >= -90 AND dec <= 90

  - name: PlanetProperties
    "@id": "#PlanetProperties"
    description: Properties for ExoMAST planets
    primaryKey: 
    - "#PlanetProperties.id"

    columns:
    - name: id
      "@id": "#PlanetProperties.id"
      datatype: long
      description: Main source identifier
      ivoa:ucd: meta.id;meta.main
    - name: orbital_period
      "@id": "#PlanetProperties.orbital_period"
      datatype: float
      description: Orbital period in days
      fits:tunit: day
      ivoa:ucd: time.period.revolution
    - name: orbital_period_error
      "@id": "#PlanetProperties.orbital_period_error"
      datatype: float
      description: Uncertainty of orbital period in days
      fits:tunit: day
      ivoa:ucd: stat.error;time.period.revolution
    - name: orbital_period_ref
      "@id": "#PlanetProperties.orbital_period_ref"
      datatype: long
      description: Publication identifier for orbital period
      ivoa:ucd: meta.bib;time.period.revolution
    - name: tess_id
      "@id": "#PlanetProperties.tess_id"
      datatype: long
      description: TESS identifier
      ivoa:ucd: meta.id


    constraints:
      - name: PlanetProperties_id_Sources_id
        "@type": "ForeignKey"
        "@id": "#FK_PlanetProperties_id_Source_id"
        description: Link PlanetProperties to Sources table
        columns:
        - "#PlanetProperties.id"
        referencedColumns:
        - "#Sources.id"
      - name: PlanetProperties_id_Publications_id
        "@type": "ForeignKey"
        "@id": "#FK_PlanetProperties_id_Publications_id"
        description: Link PlanetProperties to Publications table
        columns:
        - "#PlanetProperties.orbital_period_ref"
        referencedColumns:
        - "#Publications.id"

  - name: Publications
    "@id": "#Publications"
    description: Publications/references for values in database
    primaryKey:
    - "#Publications.id"

    columns:
    - name: id
      "@id": "#Publications.id"
      datatype: long
      description: Publication internal identifier
      ivoa:ucd: meta.id;meta.main
    - name: reference
      "@id": "#Publications.reference"
      datatype: string
      length: 100
      description: Publication reference name (eg, Author, et al. 2021)
      ivoa:ucd: meta.bib
      nullable: false
    - name: ref
      "@id": "#Publications.bibcode"
      datatype: string
      length: 30
      description: Publication bibcode
      ivoa:ucd: meta.bib.bibcode
